import { Component } from '@angular/core';
import { Productos } from '../productos';

@Component({
  selector: 'app-lista-productos',
  imports: [],
  templateUrl: './lista-productos.component.html',
  styleUrl: './lista-productos.component.css'
})
export class ListaProductosComponent {
  productos:Productos[] =[
    {id:1, nombre:"Coca cola", precio:25.5, categoria:"gaseosa"},
    {id:2, nombre:"Inka cola" , categoria:"gaseosa"},
    {id:3, nombre:"Choco soda", precio:25.5, categoria: 'galleta'},
    {id:4, nombre:"morochas", categoria:'galleta'},
    {id:5, nombre:"Sublime", precio:25.5, categoria:'chocolate'},
    {id:6, nombre:"Princesa", categoria:'chocolate'},
    {id:7, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:8, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:9, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:1, nombre:"Coca cola", precio:25.5, categoria:"gaseosa"},
    {id:2, nombre:"Inka cola" , categoria:"gaseosa"},
    {id:3, nombre:"Choco soda", precio:25.5, categoria: 'galleta'},
    {id:4, nombre:"morochas", categoria:'galleta'},
    {id:5, nombre:"Sublime", precio:25.5, categoria:'chocolate'},
    {id:6, nombre:"Princesa", categoria:'chocolate'},
    {id:7, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:8, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:9, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:1, nombre:"Coca cola", precio:25.5, categoria:"gaseosa"},
    {id:2, nombre:"Inka cola" , categoria:"gaseosa"},
    {id:3, nombre:"Choco soda", precio:25.5, categoria: 'galleta'},
    {id:4, nombre:"morochas", categoria:'galleta'},
    {id:5, nombre:"Sublime", precio:25.5, categoria:'chocolate'},
    {id:6, nombre:"Princesa", categoria:'chocolate'},
    {id:7, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:8, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:9, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:1, nombre:"Coca cola", precio:25.5, categoria:"gaseosa"},
    {id:2, nombre:"Inka cola" , categoria:"gaseosa"},
    {id:3, nombre:"Choco soda", precio:25.5, categoria: 'galleta'},
    {id:4, nombre:"morochas", categoria:'galleta'},
    {id:5, nombre:"Sublime", precio:25.5, categoria:'chocolate'},
    {id:6, nombre:"Princesa", categoria:'chocolate'},
    {id:7, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:8, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:9, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:1, nombre:"Coca cola", precio:25.5, categoria:"gaseosa"},
    {id:2, nombre:"Inka cola" , categoria:"gaseosa"},
    {id:3, nombre:"Choco soda", precio:25.5, categoria: 'galleta'},
    {id:4, nombre:"morochas", categoria:'galleta'},
    {id:5, nombre:"Sublime", precio:25.5, categoria:'chocolate'},
    {id:6, nombre:"Princesa", categoria:'chocolate'},
    {id:7, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:8, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:9, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:1, nombre:"Coca cola", precio:25.5, categoria:"gaseosa"},
    {id:2, nombre:"Inka cola" , categoria:"gaseosa"},
    {id:3, nombre:"Choco soda", precio:25.5, categoria: 'galleta'},
    {id:4, nombre:"morochas", categoria:'galleta'},
    {id:5, nombre:"Sublime", precio:25.5, categoria:'chocolate'},
    {id:6, nombre:"Princesa", categoria:'chocolate'},
    {id:7, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:8, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:9, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:1, nombre:"Coca cola", precio:25.5, categoria:"gaseosa"},
    {id:2, nombre:"Inka cola" , categoria:"gaseosa"},
    {id:3, nombre:"Choco soda", precio:25.5, categoria: 'galleta'},
    {id:4, nombre:"morochas", categoria:'galleta'},
    {id:5, nombre:"Sublime", precio:25.5, categoria:'chocolate'},
    {id:6, nombre:"Princesa", categoria:'chocolate'},
    {id:7, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:8, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    {id:9, nombre:"triangulo", precio:25.5, categoria:'chocolate'},
    
    
  ];
}
